include:
  - ${MYLOKI_FOLDER_ROOT}/myloki/docker-compose.yml

services:
    # 後端服務
    backend:
        build: . # 使用 當前目錄中的 Dockerfile
        container_name: modern_auth_api # 指定容器名稱，方便識別
        image: modern_auth_api # image名稱
        ports:
            - "7073:8080" # 我的電腦 7073 -> 對應容器內部 8080
        environment:
            - TZ=Asia/Taipei
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV}
            - ConnectionStrings__DefaultConnection=${CONN_STR_DEFAULT}
            - SecurityKey=${SECETKEY}
            - MailServerSetting__Password=${MAIL_SERVER_PWD}
            - Supabase__Url=${SUPABASE_URL}
            - Supabase__ApiKey=${SUPABASE_APIKEY}
            - ResendApiKey=${RESEND_APIKEY}
            - Redis__ConnectionString=${REDIS_CONN}
            - RabbitMq__ConnectionString=${RABBITMQ_CONN}
            - Serilog__WriteTo__1__Args__uri=${LOKI_URI}
        volumes:
          - ./modern_auth_api/logs:/app/logs
        extra_hosts:
            - "host.docker.internal:host-gateway" # 讓 Linux 容器認得 host.docker.internal
        depends_on:
            myrabbitmq:
                condition: service_healthy
            myredis:
                condition: service_started
            loki:
                condition: service_started
    myredis:
       image: redis:alpine
       ports:
          - "6379:6379"
       command: redis-server --requirepass ${REDIS_PWD}
    myrabbitmq:
       image: rabbitmq:4-management
       ports:
          - "5672:5672" # 連線
          - "15672:15672" # 管理介面
       environment:
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PWD}
       volumes:
          - rabbitmq_data:/var/lib/rabbitmq
       # 幫 RabbitMQ 健康檢查
       healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
        interval: 5s
        timeout: 3s
        retries: 5
volumes:
    rabbitmq_data: